Repository mongoose-os-apps/shelly-homekit, pull requests merged in 2021-02, with the labels that each got.

#433 Valve
  README.md
  fs/index.html.gz
  fs_src/index.html
  fs_src/script.js
  mos.yml
  src/shelly_common.hpp
  src/shelly_hap_outlet.cpp
  src/shelly_hap_valve.cpp
  src/shelly_hap_valve.hpp
  src/shelly_main.cpp
  src/shelly_switch.cpp
Labels: new HAP type

#458 fix hap code validation
  fs/index.html.gz
  fs_src/script.js
Labels: webUI

#440 add confirm step to some UI actions
  fs/index.html.gz
  fs_src/script.js
Labels: webUI

#439 Load screen
  fs_src/index.html
  fs_src/script.js
Labels: webUI

#484 Js cleanup
  fs_src/script.js
Labels: webUI

#489 [webui] fix dateStringToSeconds function.
  fs_src/script.js
Labels: webUI

#486 [webUI] change relay state control to a slider.
  fs_src/index.html
  fs_src/script.js
Labels: webUI

#488 improve mobile layout and split system into system and firmware
  fs_src/index.html
  fs_src/script.js
  fs_src/style.css
Labels: webUI

#490 [webui] auto_off hide auto_off_delay when disabled.
  fs_src/index.html
  fs_src/script.js
Labels: webUI

#483 improve button css
  fs_src/index.html
  fs_src/style.css
Labels: webUI

#462 add invert output option
  fs_src/index.html
  fs_src/script.js
  mos.yml
  src/shelly_hap_switch.cpp
  src/shelly_main.cpp
  src/shelly_output.cpp
  src/shelly_output.hpp
  src/shelly_switch.cpp
Labels: enhancement, webUI
